Workaround for using old bundler on Travis
Getting:

    NoMethodError: undefined method `spec' for nil:NilClass

From Travis because of changes made in Bundler.